### ISSUE TITLE
Does view data still have the intentions of only seeing the 10 most recent entries?

### ISSUE THREAD

**Issue by dulce-mezaf** [xyeras/AnimalFarm#22]
If so, then does the analytics base off of the 10 or all the entries (even the ones that do not show)?

**Comment by speedy1096** [comment]
Nice catch. Sorry for the late response.

Right now it is okay to have all of the entries in one table. If we continue this project we can do 10 entries on a page and the rest on different pages like when you google something.

**Comment by dulce-mezaf** [comment]
No worries! Okay so if we do it like that for now maybe we can have the data analytics show up first at the top of the entries that way they dont get overshadowed when theres a bunch of entries ?? @speedy1096

**Comment by speedy1096** [comment]
Sure.
