### ISSUE TITLE
The heat check area of the app is the same from last semester?

### ISSUE THREAD

**Issue by dulce-mezaf** [xyeras/AnimalFarm#23]
Has anyone worked/updated this part of the app this semester? @xyeras @speedy1096 @kat-saldivar

**Comment by speedy1096** [comment]
I haven't. It should be a simply fix. The files that update the database
should be the same as addMore.html.

**Comment by dulce-mezaf** [comment]
okay! @kat-saldivar and I were talking about this yesterday.. We might need to make sure this still works
