### ISSUE TITLE
Finally done! Then I push and pull and my work was gone!

### ISSUE THREAD

**Issue by dulce-mezaf** [xyeras/AnimalFarm#6]
Afraid to push and pull from github because I just did it a  while ago and all my work from Sat 11.4.17 was gone and other peoples pages got messed up too because I had done some minor edits there... Fixed everything and did rework but I am afraid to push now.. I just saved the work  in another file on my computer.. We need to figure out how to use github properly before it gets worse.

**Comment by speedy1096** [comment]
Just push the files that you have edited and talk with anyone else who may be pushing those files to github to make sure that you are not pushing the different versions of the same file.
