### ISSUE TITLE
Search Data Search Options

### ISSUE THREAD

**Issue by kat-saldivar** [xyeras/AnimalFarm#8]
For the Searchdata.html page, the select option works when opening from my file browser, but it doesn't work when the same file is uploaded from the website.

**Comment by dulce-mezaf** [comment]
what do you mean by uploaded from the website?

**Comment by kat-saldivar** [comment]
I meant that it doesn't work when i'm on the website itself
but it works when i open it from the file browser

**Comment by dulce-mezaf** [comment]
You fixed it! The jQuery was supposed to be called before the js, also had some redundant files in there..
